version: "3.9"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic-rag-dev
    volumes:
      - .:/workspace:cached
    networks:
      - app_network
    depends_on:
      - valkey
      - vector-db
      - mongodb
    command: sleep infinity

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mongodb_data:
  qdrant_data:

networks:
  app_network:
    driver: bridge
